import 'dart:ui';
import 'package:checklist_app/entity/task.dart';

class ConstText {
  static final appTitle = "Simple Check App";
  static final todoListView = "カイモノリスト";
  static final todoEditView = "Check Edit";
  static final todoCreateView = "New List";
  static final start = "start";
  static final noTask = "No task";
  static final cardTitle = "Name";
  static final cardIcon = "Icon";
  static final cardDate = "Limit Date";
  static final cardTask = "Task";
  static final cardAdd = "Add";
  static final cardOK = "OK";
  static final cardCopy = "Copy";
  static final cardAddNewItem = "Add new item";
}

class AppColors {
  static const Color DEFAULT_COLOR = Color(0xcc0eb4c2);
  static const Color DEFAULT_COLOR_LIGHT = Color(0xcc98EAF1);
  static const Color DEFAULT_COLOR_DARK = Color(0xff0eb4c2);
  static const Color DEFAULT_COLOR_SELECTED = Color(0xff058590);
  static const List<Color> avatarColors = [
    Color(0xffD10263),
    Color(0xffF29130),
    Color(0xff0EB4C2),
    Color(0xffAF30F2),
    Color(0xff3044F2),
    Color(0xff1ED102),
  ];
  static const List<String> icons = [
    'assets/images/shopping.png',
    'assets/images/basketball.png',
    'assets/images/pin.png',
    'assets/images/drink.png',
    'assets/images/muscle.png',
    'assets/images/briefcase.png',
  ];
  static const List<String> iconsSelected = [
    'assets/images/shopping_selected.png',
    'assets/images/basketball_selected.png',
    'assets/images/pin_selected.png',
    'assets/images/drink_selected.png',
    'assets/images/muscle_selected.png',
    'assets/images/briefcase_selected.png',
  ];
}

class Preset {
  static const Map<String, String> items = {
    "人参": "野菜",
    "玉ねぎ": "野菜",
    "じゃがいも": "野菜",
    "トマト": "野菜",
    "ねぎ": "野菜",
    "万能ねぎ": "野菜",
    "セロリ": "野菜",
    "キャベツ": "野菜",
    "れんこん": "野菜",
    "なす": "野菜",
    "アスパラガス": "野菜",
    "オクラ": "野菜",
    "白菜": "野菜",
    "大根": "野菜",
    "きゅうり": "野菜",
    "ごぼう": "野菜",
    "ゴーヤ": "野菜",
    "ピーマン": "野菜",
    "レタス": "野菜",
    "ブロッコリー": "野菜",
    "小松菜": "野菜",
    "かぼちゃ": "野菜",
    "ズッキーニ": "野菜",
    "かぶ": "野菜",
    "もやし": "野菜",
    "冬瓜": "野菜",
    "にら": "野菜",
    "春菊": "野菜",
    "ほうれん草": "野菜",
    "たけのこ": "野菜",
    "モロヘイヤ": "野菜",
    "コーン（とうもろこし）": "野菜",
    "チンゲンサイ": "野菜",
    "カリフラワー": "野菜",
    "菜の花": "野菜",
    "ふき": "野菜",
    "柿": "野菜",
    "しめじ": "野菜",
    "しいたけ": "野菜",
    "マッシュルーム": "野菜",
    "エリンギ": "野菜",
    "まいたけ": "野菜",
    "えのき": "野菜",
    "里芋": "野菜",
    "山芋": "野菜",
    "さつまいも": "野菜",
    "大豆": "野菜",
    "そら豆": "野菜",
    "枝豆": "野菜",
    "ピーナッツ": "野菜",
    "鶏もも": "肉",
    "鶏むね": "肉",
    "鶏ささみ": "肉",
    "鶏手羽": "肉",
    "砂肝": "肉",
    "鶏骨付き肉": "肉",
    "豚肉": "肉",
    "豚もも": "肉",
    "豚こま": "肉",
    "豚ロース": "肉",
    "豚バラ": "肉",
    "豚カツ": "肉",
    "牛肉": "肉",
    "牛こま切れ肉": "肉",
    "牛もも肉": "肉",
    "牛切り落とし肉": "肉",
    "牛薄切り肉": "肉",
    "牛バラ肉": "肉",
    "牛すじ": "肉",
    "牛ロース": "肉",
    "ひき肉": "肉",
    "豚ひき肉": "肉",
    "合びき肉": "肉",
    "鶏ひき肉": "肉",
    "牛ひき肉": "肉",
    "ベーコン": "肉",
    "ハム": "肉",
    "ソーセージ": "肉",
    "焼き豚・チャーシュー": "肉",
    "ラム肉": "肉",
    "鴨肉": "肉",
    "米": "穀類",
    "そうめん": "穀類",
    "スパゲティ": "穀類",
    "パスタ": "穀類",
    "うどん": "穀類",
    "そば": "穀類",
    "もち": "穀類",
    "パン": "穀類",
    "いわし": "魚",
    "あじ": "魚",
    "白身魚": "魚",
    "まぐろ": "魚",
    "さば": "魚",
    "かじき": "魚",
    "たい": "魚",
    "うなぎ": "魚",
    "かつお": "魚",
    "さけ": "魚",
    "すずき": "魚",
    "さんま": "魚",
    "かれい": "魚",
    "たら": "魚",
    "ぶり": "魚",
    "きんめだい": "魚",
    "さわら": "魚",
    "あなご": "魚",
    "えび": "魚介類",
    "かに": "魚介類",
    "あさり、しじみ": "魚介類",
    "かき": "魚介類",
    "はまぐり": "魚介類",
    "ほたて": "魚介類",
    "たらこ": "魚介類",
    "明太子": "魚介類",
    "スモークサーモン": "魚介類",
    "アンチョビ": "魚介類",
    "いか": "魚介類",
    "ツナ": "魚介類",
    "たこ": "魚介類",
    "卵": "乳製品",
    "うずら卵": "乳製品",
    "生クリーム": "乳製品",
    "ヨーグルト": "乳製品",
    "チーズ": "乳製品",
    "牛乳": "乳製品",
    "油揚げ": "大豆製品",
    "豆腐": "大豆製品",
    "納豆": "大豆製品",
    "厚揚げ": "大豆製品",
    "高野豆腐": "大豆製品",
    "絹ごし豆腐": "大豆製品",
    "こんにゃく": "その他",
    "ちりめんじゃこ": "その他",
    "切り干し大根": "その他",
    "キムチ": "その他",
    "わかめ": "その他",
    "ひじき": "その他",
    "さつま揚げ": "その他",
  };
}
